### PR TITLE
Pass options to Validator

### PR DESCRIPTION
**Pull request by seanpdoyle**
Resolves [#9] and [#10].

[#9]: https://github.com/thoughtbot/json-matchers/issues/9
[#10]: https://github.com/thoughtbot/json-matchers/issues/10

### CODE REVIEW

**Comment by mike-burns** [comment]
Woot!

The code looks solid. Can you update the README, please?

**Comment by seanpdoyle** [comment]
@mike-burns I've updated the README and the CHANGELOG

Unfortunately, the gem's [list of available options](https://github.com/ruby-json-schema/json-schema/blob/2.2.4/lib/json-schema/validator.rb#L160-L162) isn't very .... polished ... 

Digging that up also made me realize that I'm using v `2.2.5` of the gem, which doesn't seem to support your `fragment:` argument.

I'll try upgrading versions in a separate PR.

**Comment by mike-burns** [comment]
Right on, and nice catch. Looks good to merge.

**Comment by seanpdoyle** [comment]
@mike-burns on further inspection, the `:fragment` option exists

https://github.com/ruby-json-schema/json-schema/blob/2.2.4/lib/json-schema/validator.rb#L182-L185

Since the docs are lacking, I'm not sure if that'll get passed along, but it's worth trying.

**Comment by mike-burns** [comment]
Well it is documented here: https://github.com/ruby-json-schema/json-schema/tree/2.2.4#validate-against-a-fragment-of-a-supplied-schema

**Comment by seanpdoyle** [comment]
:tada:

**Pull request merged**
